Repository mendix/Atlas-UI-Framework, pull requests merged in 2020-09, with the labels that each got.

#76 Fix dark mode date picker iOS
  styles/native/js/core/widgets/datepicker.js
  styles/native/ts/core/widgets/datepicker.ts
  styles/native/ts/types/widgets.d.ts
Labels: MX 8.14

#83 Remove preview files
  index-phone-preview.html
  index-tablet-preview.html
  resources/phone.png
  resources/tablet.png
  styles/web/sass/main.scss
  styles/web/sass/ui_resources/atlas_ui_resources/layouts/_layout-atlas-device-wrapper.scss
Labels: MX 8.14

#78 Port fix native date picker iOS text color dark mode
  styles/native/ts/core/widgets/datepicker.ts
Labels: Atlas 3.0, MX 8.14

#88 Add focus styles
  styles/native/ts/core/widgets/dropdown.ts
  styles/native/ts/core/widgets/referenceselector.ts
  styles/native/ts/core/widgets/textarea.ts
  styles/native/ts/core/widgets/textbox.ts
  styles/native/ts/types/widgets.d.ts
Labels: Atlas 3.0
